algorithm: freesequencematch
save_dir: ./saved_models/usb_cv
save_name: freesequencematch_motor30_AdamW_u4
resume: False
load_path: ./saved_models/usb_cv/freesequencematch_motor30_u4/model_best_acc.pth
overwrite: True
use_tensorboard: True
epoch: 20
num_train_iter: 200000
num_log_iter: 2000
num_eval_iter: 2000
batch_size: 8
eval_batch_size: 8
num_warmup_iter: 2000
num_labels: 5
uratio: 4
ema_m: 0.999
T: 0.5
thresh_warmup: True
p_cutoff: 0.95                                                                      
in_loss_ratio: 1.0
ulb_loss_ratio: 1.0
ent_loss_ratio: 0.001                              
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0001
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
net: vit_small_patch16_224
net_from_name: False
data_dir: /home/linhdt/Desktop/hoangcm/data
dataset: motor30per
train_sampler: RandomSampler
num_classes: 5
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: /home/linhdt/Desktop/hoangcm/code/Semi-supervised-learning/pretrained_weights/vit_small_patch16_224_mlp_im_1k_224.pth
ema: True
hard_label: True
