algorithm: freesequencematch
save_dir: ./saved_models/usb_cv
save_name: freesequencematch_cifar10_u1
resume: False
load_path: ./saved_models/usb_cv/freesequencematch_motor30_u4/model_best_acc.pth
overwrite: True
use_tensorboard: True
epoch: 20
num_train_iter: 200000
num_log_iter: 2000
num_eval_iter: 2000
batch_size: 8
eval_batch_size: 8
num_warmup_iter: 2000
num_labels: 10
uratio: 1
ema_m: 0.999
T: 0.5
thresh_warmup: True
p_cutoff: 0.95
ulb_loss_ratio: 1.0
in_loss_ratio: 1.0
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 5e-5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
net: vit_small_patch2_32
net_from_name: False
data_dir: /home/hoang.thuy.ha/Semi-supervised-learning/data
dataset: cifar10_motor
train_sampler: RandomSampler
num_classes: 10
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
gpu: 0
use_pretrain: True
pretrain_path: /home/hoang.thuy.ha/Semi-supervised-learning/vit_small_patch2_32_mlp_im_1k_32.pth
ema: True
hard_label: True
ent_loss_ratio: 0.001